name: Aggiorna Feed ANSA

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: pip install feedparser requests beautifulsoup4

      - name: Esegui script
        run: |
          python generate_rss.py
          if [ -f ansa_sport_enriched.xml ]; then
            echo "✅ OK: Feed generato"
            head -n 3 ansa_sport_enriched.xml
          else
            echo "❌ ERRORE: File XML non creato!"
            exit 1
          fi

      - name: Pubblica su gh-pages
        run: |
          git config user.name "francescofellini"
          git config user.email "francesco.fellini@example.com"
          
          # Crea o entra nel branch gh-pages
          git checkout -B gh-pages || exit 1
          
          # Copia il file XML nella root
          cp ansa_sport_enriched.xml . || exit 1
          
          # Aggiungi e committa
          git add ansa_sport_enriched.xml
          git commit -m "Aggiornato feed ANSA $(date)" || exit 1
          
          # Push forzato
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/francescofellini/ansafeed.git gh-pages
