name: Aggiorna Feed ANSA

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: pip install feedparser requests beautifulsoup4

      - name: Esegui script
        run: |
          python generate_rss.py
          if [ -f ansa_sport_enriched.xml ]; then
            echo "✅ OK: Feed generato"
            head -n 5 ansa_sport_enriched.xml
          else
            echo "❌ ERRORE: File XML non creato!"
            exit 1
          fi

      - name: Pubblica su GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
